version: "3.9"

services:
  backend:
    container_name: backend
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser --username root --email root@root.com && gunicorn social_network.wsgi --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - "db:database"
    depends_on:
      - db
  
  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U DjangoAdmin -d djangodb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    
volumes:
  pg_data: